const Data = [
	{
		id: 98,
		category: 'experience',
		icon: 'icon-briefcase',
		year: 'Mar 2024 - Present',
		title: 'Technical facilitator of "Yo Puedo Programar"',
		entity: 'Junior Achievement Santa Fe',
	},
	{
		id: 99,
		category: 'experience',
		icon: 'icon-briefcase',
		year: 'Feb 2023 - Present',
		title: 'Coordinator and technical facilitator of "Yo Puedo Programar"',
		entity: 'Junior Achievement Santa Fe',
	},
	{
		id: 100,
		category: 'experience',
		icon: 'icon-briefcase',
		year: 'Dec 2022 - Present',
		title: 'Web Developer',
		entity: 'Efecto Digital',
	},
	{
		id: 101,
		category: 'experience',
		icon: 'icon-briefcase',
		year: '2022 - Present',
		title: 'Freelance Front-End Developer',
		entity: 'Freelance',
	},
	{
		id: 103,
		category: 'experience',
		icon: 'icon-briefcase',
		year: 'March 2018 - November 2019',
		title: 'Law firm assistant',
		entity: 'Law firm Badalotti, Cristófaro & Cavallieri',
	},
	{
		id: 104,
		category: 'education',
		icon: 'icon-graduation',
		year: 'Jun 2023 - Present',
		title: 'University Program in Programming',
		entity: 'National University of Technology',
	},
	{
		id: 104,
		category: 'education',
		icon: 'icon-graduation',
		year: 'May 2023',
		title: 'UX Design: user experience UX/UI + Figma 2023',
		entity: 'Javier Cañas from Udemy',
	},
	{
		id: 105,
		category: 'education',
		icon: 'icon-graduation',
		year: 'April 2023',
		title: 'JavaScript & jQuery - Certification Course for Beginners',
		entity: 'YouAccel Training from Udemy',
	},
	{
		id: 106,
		category: 'education',
		icon: 'icon-graduation',
		year: 'January 2023',
		title: 'Learn PHP - For Beginners',
		entity: 'YouAccel Training from Udemy',
	},
	{
		id: 107,
		category: 'education',
		icon: 'icon-graduation',
		year: 'November 2022',
		title: 'CSS3 Course',
		entity: 'Jordan Alex from AlexCG Design',
	},
	{
		id: 108,
		category: 'education',
		icon: 'icon-graduation',
		year: 'August 2022',
		title: 'Programming from Scratch - University Level',
		entity: 'Maxi Programa',
	},
	{
		id: 109,
		category: 'education',
		icon: 'icon-graduation',
		year: 'April 2022',
		title: 'React Course',
		entity: 'Coderhouse',
	},
	{
		id: 110,
		category: 'education',
		icon: 'icon-graduation',
		year: 'March 2022',
		title: 'Javascript Course',
		entity: 'Coderhouse',
	},
	{
		id: 111,
		category: 'education',
		icon: 'icon-graduation',
		year: 'January 2022',
		title: 'Web Development Course',
		entity: 'Coderhouse',
	},
	{
		id: 112,
		category: 'education',
		icon: 'icon-education',
		year: 'July 2021 - October 2021',
		title: 'Strangebox',
		entity: 'PWA Games and PWA website we developed with a colleague',
	},
	{
		id: 113,
		category: 'education',
		icon: 'icon-graduation',
		year: 'October 2019',
		title: 'Learn CSS Course',
		entity: 'Codecademy',
	},
	{
		id: 114,
		category: 'education',
		icon: 'icon-graduation',
		year: '2019 - Present',
		title: 'Tutorials, documentation and free courses',
		entity: 'Platzi, Youtube, Codecademy, Blogs',
	},
	{
		id: 115,
		category: 'education',
		icon: 'icon-graduation',
		year: '2014 - 2020',
		title: 'Advanced student in Law school (not finished)',
		entity: 'Universidad Nacional de Rosario',
	},
];

export default Data;
