const Data = [
	{
		id: 1,
		category: 'education',
		icon: 'icon-graduation',
		year: 'November 2022',
		title: 'CSS3 Course',
		entity: 'Jordan Alex from AlexCG Design',
	},
	{
		id: 2,
		category: 'education',
		icon: 'icon-graduation',
		year: 'August 2022 - Present',
		title: 'Programming From Scratch - University Level',
		entity: 'Maxi Programa',
	},
	{
		id: 3,
		category: 'education',
		icon: 'icon-graduation',
		year: 'November 2022',
		title: 'CSS3 Course',
		entity: 'Jordan Alex from AlexCG Design',
	},
	{
		id: 4,
		category: 'education',
		icon: 'icon-graduation',
		year: 'April 2022',
		title: 'React Course',
		entity: 'Coderhouse',
	},
	{
		id: 5,
		category: 'education',
		icon: 'icon-graduation',
		year: 'March 2022',
		title: 'Javascript Course',
		entity: 'Coderhouse',
	},
	{
		id: 6,
		category: 'education',
		icon: 'icon-graduation',
		year: 'January 2022',
		title: 'Web Development Course',
		entity: 'Coderhouse',
	},
	{
		id: 7,
		category: 'education',
		icon: 'icon-graduation',
		year: 'October 2019',
		title: 'Learn CSS Course',
		entity: 'Codecademy',
	},
	{
		id: 8,
		category: 'education',
		icon: 'icon-graduation',
		year: '2019 - Present',
		title: 'Tutorials, documentation and free courses',
		entity: 'Platzi, Youtube, Codecademy, Blogs',
	},
	{
		id: 9,
		category: 'education',
		icon: 'icon-graduation',
		year: '2014 - 2020',
		title: 'Advanced student in Law school (Abandoned)',
		entity: 'Universidad Nacional de Rosario',
	},
	{
		id: 10,
		category: 'experience',
		icon: 'icon-briefcase',
		year: '2022 - Present',
		title: 'Freelance Front-End Developer',
		entity: 'Freelance',
	},
	{
		id: 11,
		category: 'experience',
		icon: 'icon-briefcase',
		year: 'July 2021 - October 2021',
		title: 'Strangebox',
		entity: 'Games and pwas website we developed with a colleague',
	},
	{
		id: 12,
		category: 'experience',
		icon: 'icon-briefcase',
		year: 'March 2018 - November 2019',
		title: 'Law firm assistant',
		entity: 'Law firm Badalotti, Cristófaro & Cavallieri',
	},
];

export default Data;
